"use client"

import { createContext, useContext, useState, useCallback, type ReactNode } from "react"

export type Language = "en" | "hi" | "ta" | "te" | "mr" | "bn"

interface LanguageInfo {
  code: Language
  name: string
  nativeName: string
}

export const languages: LanguageInfo[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
]

type TranslationKey =
  | "nav.home"
  | "nav.advisor"
  | "nav.market"
  | "nav.schemes"
  | "nav.language"
  | "hero.title"
  | "hero.subtitle"
  | "hero.cta"
  | "hero.certified"
  | "features.soil.title"
  | "features.soil.desc"
  | "features.demand.title"
  | "features.demand.desc"
  | "features.price.title"
  | "features.price.desc"
  | "features.weather.title"
  | "features.weather.desc"
  | "features.scheme.title"
  | "features.scheme.desc"
  | "features.water.title"
  | "features.water.desc"
  | "advisor.title"
  | "advisor.subtitle"
  | "advisor.soil"
  | "advisor.state"
  | "advisor.water"
  | "advisor.submit"
  | "advisor.results"
  | "advisor.profitability"
  | "advisor.demand"
  | "advisor.supply"
  | "advisor.recommendation"
  | "advisor.waterReq"
  | "advisor.growingPeriod"
  | "advisor.days"
  | "advisor.season"
  | "advisor.tips"
  | "advisor.selectSoil"
  | "advisor.selectState"
  | "advisor.selectWater"
  | "market.title"
  | "market.subtitle"
  | "market.msp"
  | "market.current"
  | "market.trend"
  | "market.perQuintal"
  | "schemes.title"
  | "schemes.subtitle"
  | "schemes.eligibility"
  | "schemes.benefit"
  | "schemes.apply"
  | "schemes.all"
  | "schemes.subsidy"
  | "schemes.insurance"
  | "schemes.credit"
  | "schemes.infrastructure"
  | "schemes.training"
  | "footer.tagline"
  | "footer.rights"
  | "common.low"
  | "common.medium"
  | "common.high"
  | "common.veryHigh"
  | "common.shortage"
  | "common.balanced"
  | "common.surplus"
  | "common.safe"
  | "common.caution"
  | "common.warning"
  | "common.kharif"
  | "common.rabi"
  | "common.zaid"
  | "stats.farmers"
  | "stats.crops"
  | "stats.states"
  | "stats.schemes"
  | "landing.features.heading"
  | "landing.features.subheading"
  | "landing.howItWorks.heading"
  | "landing.howItWorks.subheading"
  | "landing.howItWorks.step1.title"
  | "landing.howItWorks.step1.desc"
  | "landing.howItWorks.step2.title"
  | "landing.howItWorks.step2.desc"
  | "landing.howItWorks.step3.title"
  | "landing.howItWorks.step3.desc"
  | "landing.cta.heading"
  | "landing.cta.desc"
  | "advisor.farmDetails"
  | "advisor.farmDetailsDesc"
  | "advisor.soilPh"
  | "advisor.characteristics"
  | "advisor.commonRegions"
  | "advisor.noResults"
  | "advisor.noResultsDesc"
  | "advisor.emptyTitle"
  | "advisor.emptyDesc"
  | "advisor.waterLow"
  | "advisor.waterMedium"
  | "advisor.waterHigh"
  | "advisor.moreDetails"
  | "advisor.showLess"
  | "advisor.temp"
  | "market.rising"
  | "market.stable"
  | "market.falling"
  | "market.chartTitle"
  | "market.chartDesc"
  | "market.allPrices"
  | "schemes.helpTitle"
  | "schemes.helpDesc"
  | "footer.quickLinks"
  | "footer.contact"

const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    "nav.home": "Home",
    "nav.advisor": "Crop Advisor",
    "nav.market": "Market Prices",
    "nav.schemes": "Govt Schemes",
    "nav.language": "Language",
    "hero.title": "Grow Smarter, Earn Better",
    "hero.subtitle": "Government-certified crop advisory that helps you choose the right crops based on your soil, regional demand, and market conditions.",
    "hero.cta": "Get Crop Recommendations",
    "hero.certified": "Government Certified Platform",
    "features.soil.title": "Soil Analysis",
    "features.soil.desc": "Get crop recommendations based on your soil type, pH level, and nutrient content.",
    "features.demand.title": "Supply-Demand Balance",
    "features.demand.desc": "Know what others are growing. Avoid surplus, prevent price crashes.",
    "features.price.title": "Market Prices",
    "features.price.desc": "Track real-time crop prices, MSP rates, and price trends across mandis.",
    "features.weather.title": "Weather Advisory",
    "features.weather.desc": "Get local weather forecasts and climate-smart farming recommendations.",
    "features.scheme.title": "Govt Schemes",
    "features.scheme.desc": "Access all government subsidies, insurance, and support schemes in one place.",
    "features.water.title": "Water Management",
    "features.water.desc": "Optimize irrigation based on crop needs and water availability in your region.",
    "advisor.title": "Crop Advisor",
    "advisor.subtitle": "Enter your farm details to get personalized crop recommendations",
    "advisor.soil": "Soil Type",
    "advisor.state": "State",
    "advisor.water": "Water Availability",
    "advisor.submit": "Get Recommendations",
    "advisor.results": "Recommended Crops",
    "advisor.profitability": "Profitability Score",
    "advisor.demand": "Demand",
    "advisor.supply": "Supply Status",
    "advisor.recommendation": "Recommendation",
    "advisor.waterReq": "Water Requirement",
    "advisor.growingPeriod": "Growing Period",
    "advisor.days": "days",
    "advisor.season": "Season",
    "advisor.tips": "Tips",
    "advisor.selectSoil": "Select your soil type",
    "advisor.selectState": "Select your state",
    "advisor.selectWater": "Select water availability",
    "market.title": "Market Prices",
    "market.subtitle": "Track current crop prices and trends",
    "market.msp": "MSP",
    "market.current": "Current Price",
    "market.trend": "Trend",
    "market.perQuintal": "per quintal",
    "schemes.title": "Government Schemes",
    "schemes.subtitle": "Find and apply for agricultural support schemes",
    "schemes.eligibility": "Eligibility",
    "schemes.benefit": "Benefit",
    "schemes.apply": "Learn More",
    "schemes.all": "All",
    "schemes.subsidy": "Subsidy",
    "schemes.insurance": "Insurance",
    "schemes.credit": "Credit",
    "schemes.infrastructure": "Infrastructure",
    "schemes.training": "Training",
    "footer.tagline": "Empowering Indian Farmers with Smart Crop Advisory",
    "footer.rights": "All rights reserved. Government of India Initiative.",
    "common.low": "Low",
    "common.medium": "Medium",
    "common.high": "High",
    "common.veryHigh": "Very High",
    "common.shortage": "Shortage",
    "common.balanced": "Balanced",
    "common.surplus": "Surplus",
    "common.safe": "Recommended",
    "common.caution": "Monitor",
    "common.warning": "Avoid",
    "common.kharif": "Kharif (Jul-Oct)",
    "common.rabi": "Rabi (Nov-Mar)",
    "common.zaid": "Zaid (Mar-Jun)",
    "stats.farmers": "Farmers Registered",
    "stats.crops": "Crops Tracked",
    "stats.states": "States Covered",
    "stats.schemes": "Govt Schemes",
    "landing.features.heading": "Everything a Farmer Needs",
    "landing.features.subheading": "One platform, all the tools for smarter agricultural decisions",
    "landing.howItWorks.heading": "How It Works",
    "landing.howItWorks.subheading": "Three simple steps to better farming decisions",
    "landing.howItWorks.step1.title": "Enter Your Farm Details",
    "landing.howItWorks.step1.desc": "Tell us your soil type, location, and water availability.",
    "landing.howItWorks.step2.title": "Get Smart Recommendations",
    "landing.howItWorks.step2.desc": "Our system analyzes supply-demand data and suggests the best crops for you.",
    "landing.howItWorks.step3.title": "Grow & Earn Better",
    "landing.howItWorks.step3.desc": "Follow the advisory, track prices, and access government schemes for support.",
    "landing.cta.heading": "Start Making Smarter Crop Decisions Today",
    "landing.cta.desc": "Join millions of Indian farmers who are already using CropGuide India to grow the right crops and earn better.",
    "advisor.farmDetails": "Farm Details",
    "advisor.farmDetailsDesc": "Enter your farm information below",
    "advisor.soilPh": "pH Range",
    "advisor.characteristics": "Characteristics",
    "advisor.commonRegions": "Common Regions",
    "advisor.noResults": "No Crops Found",
    "advisor.noResultsDesc": "No suitable crops found for the selected combination. Try changing your soil type or water availability.",
    "advisor.emptyTitle": "Select Your Farm Details",
    "advisor.emptyDesc": "Fill in the form to get personalized crop recommendations with supply-demand analysis.",
    "advisor.waterLow": "Rainfed / No Irrigation",
    "advisor.waterMedium": "Seasonal Irrigation",
    "advisor.waterHigh": "Year-round Irrigation",
    "advisor.moreDetails": "More Details",
    "advisor.showLess": "Show Less",
    "advisor.temp": "Temp",
    "market.rising": "Prices Rising",
    "market.stable": "Prices Stable",
    "market.falling": "Prices Falling",
    "market.chartTitle": "Price Comparison: Current vs MSP",
    "market.chartDesc": "Top crops by current market price (per quintal)",
    "market.allPrices": "All Crop Prices",
    "schemes.helpTitle": "Need Help Applying?",
    "schemes.helpDesc": "Call the Kisan Call Center at {phone} (toll-free) for assistance in applying for any government scheme. Available in 22 languages.",
    "footer.quickLinks": "Quick Links",
    "footer.contact": "Contact",
  },
  hi: {
    "nav.home": "होम",
    "nav.advisor": "फसल सलाहकार",
    "nav.market": "बाज़ार भाव",
    "nav.schemes": "सरकारी योजनाएं",
    "nav.language": "भाषा",
    "hero.title": "स्मार्ट खेती, बेहतर कमाई",
    "hero.subtitle": "सरकार प्रमाणित फसल सलाह जो आपकी मिट्टी, क्षेत्रीय मांग और बाज़ार स्थितियों के आधार पर सही फसल चुनने में मदद करती है।",
    "hero.cta": "फसल सिफारिशें प्राप्त करें",
    "hero.certified": "सरकार प्रमाणित मंच",
    "features.soil.title": "मिट्टी विश्लेषण",
    "features.soil.desc": "अपनी मिट्टी के प्रकार, pH स्तर और पोषक तत्वों के आधार पर फसल सिफारिशें पाएं।",
    "features.demand.title": "आपूर्ति-मांग संतुलन",
    "features.demand.desc": "जानें दूसरे किसान क्या उगा रहे हैं। अधिशेष से बचें, कीमतों में गिरावट रोकें।",
    "features.price.title": "बाज़ार भाव",
    "features.price.desc": "मंडियों में वास्तविक समय के फसल भाव, MSP दरें और मूल्य रुझान ट्रैक करें।",
    "features.weather.title": "मौसम सलाह",
    "features.weather.desc": "स्थानीय मौसम पूर्वानुमान और जलवायु-स्मार्ट खेती सिफारिशें प्राप्त करें।",
    "features.scheme.title": "सरकारी योजनाएं",
    "features.scheme.desc": "सभी सरकारी सब्सिडी, बीमा और सहायता योजनाएं एक ही जगह पर।",
    "features.water.title": "जल प्रबंधन",
    "features.water.desc": "फसल की जरूरतों और क्षेत्र में जल उपलब्धता के आधार पर सिंचाई अनुकूलित करें।",
    "advisor.title": "फसल सलाहकार",
    "advisor.subtitle": "व्यक्तिगत फसल सिफारिशें प्राप्त करने के लिए अपने खेत का विवरण दर्ज करें",
    "advisor.soil": "मिट्टी का प्रकार",
    "advisor.state": "राज्य",
    "advisor.water": "जल उपलब्धता",
    "advisor.submit": "सिफारिशें प्राप्त करें",
    "advisor.results": "अनुशंसित फसलें",
    "advisor.profitability": "लाभप्रदता स्कोर",
    "advisor.demand": "मांग",
    "advisor.supply": "आपूर्ति स्थिति",
    "advisor.recommendation": "सिफारिश",
    "advisor.waterReq": "जल आवश्यकता",
    "advisor.growingPeriod": "उगाने की अवधि",
    "advisor.days": "दिन",
    "advisor.season": "मौसम",
    "advisor.tips": "सुझाव",
    "advisor.selectSoil": "अपनी मिट्टी का प्रकार चुनें",
    "advisor.selectState": "अपना राज्य चुनें",
    "advisor.selectWater": "जल उपलब्धता चुनें",
    "market.title": "बाज़ार भाव",
    "market.subtitle": "वर्तमान फसल की कीमतें और रुझान ट्रैक करें",
    "market.msp": "एमएसपी",
    "market.current": "वर्तमान मूल्य",
    "market.trend": "रुझान",
    "market.perQuintal": "प्रति क्विंटल",
    "schemes.title": "सरकारी योजनाएं",
    "schemes.subtitle": "कृषि सहायता योजनाओं को खोजें और आवेदन करें",
    "schemes.eligibility": "पात्रता",
    "schemes.benefit": "लाभ",
    "schemes.apply": "और जानें",
    "schemes.all": "सभी",
    "schemes.subsidy": "सब्सिडी",
    "schemes.insurance": "बीमा",
    "schemes.credit": "ऋण",
    "schemes.infrastructure": "बुनियादी ढांचा",
    "schemes.training": "प्रशिक्षण",
    "footer.tagline": "स्मार्ट फसल सलाह से भारतीय किसानों को सशक्त बनाना",
    "footer.rights": "सर्वाधिकार सुरक्षित। भारत सरकार की पहल।",
    "common.low": "कम",
    "common.medium": "मध्यम",
    "common.high": "अधिक",
    "common.veryHigh": "बहुत अधिक",
    "common.shortage": "कमी",
    "common.balanced": "संतुलित",
    "common.surplus": "अधिशेष",
    "common.safe": "अनुशंसित",
    "common.caution": "निगरानी",
    "common.warning": "बचें",
    "common.kharif": "खरीफ (जुल-अक्टू)",
    "common.rabi": "रबी (नव-मार्च)",
    "common.zaid": "ज़ायद (मार्च-जून)",
    "stats.farmers": "पंजीकृत किसान",
    "stats.crops": "ट्रैक की गई फसलें",
    "stats.states": "राज्य शामिल",
    "stats.schemes": "सरकारी योजनाएं",
    "landing.features.heading": "एक किसान को जो चाहिए सब कुछ",
    "landing.features.subheading": "एक मंच, स्मार्ट कृषि निर्णयों के लिए सभी उपकरण",
    "landing.howItWorks.heading": "यह कैसे काम करता है",
    "landing.howItWorks.subheading": "बेहतर खेती के निर्णयों के लिए तीन सरल कदम",
    "landing.howItWorks.step1.title": "अपने खेत का विवरण दर्ज करें",
    "landing.howItWorks.step1.desc": "अपनी मिट्टी का प्रकार, स्थान और जल उपलब्धता बताएं।",
    "landing.howItWorks.step2.title": "स्मार्ट सिफारिशें पाएं",
    "landing.howItWorks.step2.desc": "हमारी प्रणाली आपूर्ति-मांग डेटा का विश्लेषण करती है और आपके लिए सर्वोत्तम फसलें सुझाती है।",
    "landing.howItWorks.step3.title": "बेहतर उगाएं और कमाएं",
    "landing.howItWorks.step3.desc": "सलाह का पालन करें, कीमतें ट्रैक करें और सहायता के लिए सरकारी योजनाओं तक पहुंचें।",
    "landing.cta.heading": "आज ही स्मार्ट फसल निर्णय लेना शुरू करें",
    "landing.cta.desc": "लाखों भारतीय किसानों से जुड़ें जो पहले से ही CropGuide India का उपयोग कर सही फसलें उगा रहे हैं।",
    "advisor.farmDetails": "खेत का विवरण",
    "advisor.farmDetailsDesc": "नीचे अपने खेत की जानकारी दर्ज करें",
    "advisor.soilPh": "pH श्रेणी",
    "advisor.characteristics": "विशेषताएं",
    "advisor.commonRegions": "सामान्य क्षेत्र",
    "advisor.noResults": "कोई फसल नहीं मिली",
    "advisor.noResultsDesc": "चयनित संयोजन के लिए कोई उपयुक्त फसल नहीं मिली। मिट्टी का प्रकार या जल उपलब्धता बदलें।",
    "advisor.emptyTitle": "अपने खेत का विवरण चुनें",
    "advisor.emptyDesc": "आपूर्ति-मांग विश्लेषण के साथ व्यक्तिगत फसल सिफारिशें प्राप्त करने के लिए फॉर्म भरें।",
    "advisor.waterLow": "वर्षा आधारित / बिना सिंचाई",
    "advisor.waterMedium": "मौसमी सिंचाई",
    "advisor.waterHigh": "साल भर सिंचाई",
    "advisor.moreDetails": "अधिक विवरण",
    "advisor.showLess": "कम दिखाएं",
    "advisor.temp": "तापमान",
    "market.rising": "कीमतें बढ़ रही हैं",
    "market.stable": "कीमतें स्थिर हैं",
    "market.falling": "कीमतें गिर रही हैं",
    "market.chartTitle": "मूल्य तुलना: वर्तमान बनाम MSP",
    "market.chartDesc": "वर्तमान बाज़ार मूल्य के अनुसार शीर्ष फसलें (प्रति क्विंटल)",
    "market.allPrices": "सभी फसल भाव",
    "schemes.helpTitle": "आवेदन में मदद चाहिए?",
    "schemes.helpDesc": "किसी भी सरकारी योजना में आवेदन के लिए किसान कॉल सेंटर पर कॉल करें {phone} (टोल-फ्री)। 22 भाषाओं में उपलब्ध।",
    "footer.quickLinks": "त्वरित लिंक",
    "footer.contact": "संपर्क",
  },
  ta: {
    "nav.home": "முகப்பு",
    "nav.advisor": "பயிர் ஆலோசகர்",
    "nav.market": "சந்தை விலை",
    "nav.schemes": "அரசு திட்டங்கள்",
    "nav.language": "மொழி",
    "hero.title": "புத்திசாலியாக விவசாயம், சிறந்த வருமானம்",
    "hero.subtitle": "உங்கள் மண், பிராந்திய தேவை மற்றும் சந்தை நிலைமைகளின் அடிப்படையில் சரியான பயிர்களை தேர்ந்தெடுக்க உதவும் அரசு சான்றளிக்கப்பட்ட பயிர் ஆலோசனை.",
    "hero.cta": "பயிர் பரிந்துரைகளைப் பெறுங்கள்",
    "hero.certified": "அரசு சான்றளிக்கப்பட்ட தளம்",
    "features.soil.title": "மண் பகுப்பாய்வு",
    "features.soil.desc": "உங்கள் மண் வகை அடிப்படையில் பயிர் பரிந்துரைகள் பெறுங்கள்.",
    "features.demand.title": "வழங்கல்-தேவை சமநிலை",
    "features.demand.desc": "மற்றவர்கள் என்�� விளைவிக்கிறார்கள் என்பதை அறியுங்கள்.",
    "features.price.title": "சந்தை விலை",
    "features.price.desc": "நிகழ்நேர பயிர் விலைகள் மற்றும் போக்குகளை கண்காணிக்கவும்.",
    "features.weather.title": "வானிலை ஆலோசனை",
    "features.weather.desc": "உள்ளூர் வானிலை முன்னறிவிப்புகளைப் பெறுங்கள்.",
    "features.scheme.title": "அரசு திட்டங்கள்",
    "features.scheme.desc": "அனைத்து அரசு மானியங்கள் ஒரே இடத்தில்.",
    "features.water.title": "நீர் மேலாண்மை",
    "features.water.desc": "பயிர் தேவைகளின் அடிப்படையில் நீர்ப்பாசனத்தை மேம்படுத்துங்கள்.",
    "advisor.title": "பயிர் ஆலோசகர்",
    "advisor.subtitle": "தனிப்பயன் பயிர் பரிந்துரைகளுக்கு விவரங்களை உள்ளிடவும்",
    "advisor.soil": "மண் வகை",
    "advisor.state": "மாநிலம்",
    "advisor.water": "நீர் கிடைக்கும் தன்மை",
    "advisor.submit": "பரிந்துரைகளைப் பெறுங்கள்",
    "advisor.results": "பரிந்துரைக்கப்பட்ட பயிர்கள்",
    "advisor.profitability": "லாப மதிப்பெண்",
    "advisor.demand": "தேவை",
    "advisor.supply": "வழங்கல் நிலை",
    "advisor.recommendation": "பரிந்துரை",
    "advisor.waterReq": "நீர் தேவை",
    "advisor.growingPeriod": "வளரும் காலம்",
    "advisor.days": "நாட்கள்",
    "advisor.season": "பருவம்",
    "advisor.tips": "குறிப்புகள்",
    "advisor.selectSoil": "மண் வகையைத் தேர்ந்தெடுக்கவும்",
    "advisor.selectState": "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    "advisor.selectWater": "நீர் கிடைக்கும் தன்மையைத் தேர்ந்தெடுக்கவும்",
    "market.title": "சந்தை விலை",
    "market.subtitle": "தற்போதைய பயிர் விலைகளைக் கண்காணிக்கவும்",
    "market.msp": "MSP",
    "market.current": "தற்போதைய விலை",
    "market.trend": "போக்கு",
    "market.perQuintal": "குவிண்டால் ஒன்றுக்கு",
    "schemes.title": "அரசு திட்டங்கள்",
    "schemes.subtitle": "விவசாய ஆதரவு திட்டங்களைக் கண்டறியவும்",
    "schemes.eligibility": "தகுதி",
    "schemes.benefit": "பலன்",
    "schemes.apply": "மேலும் அறிய",
    "schemes.all": "அனைத்தும்",
    "schemes.subsidy": "மானியம்",
    "schemes.insurance": "காப்பீடு",
    "schemes.credit": "கடன்",
    "schemes.infrastructure": "உள்கட்டமைப்பு",
    "schemes.training": "பயிற்சி",
    "footer.tagline": "புத்திசாலி பயிர் ஆலோசனையுடன் இந்திய விவசாயிகளை மேம்படுத்துதல்",
    "footer.rights": "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. இந்திய அரசின் முன்முயற்சி.",
    "common.low": "குறைவு",
    "common.medium": "நடுத்தரம்",
    "common.high": "அதிகம்",
    "common.veryHigh": "மிக அதிகம்",
    "common.shortage": "பற்றாக்குறை",
    "common.balanced": "சமநிலை",
    "common.surplus": "உபரி",
    "common.safe": "பரிந்துரைக்கப்பட்டது",
    "common.caution": "கண்காணிப்பு",
    "common.warning": "தவிர்க்கவும்",
    "common.kharif": "காரிஃப் (ஜூலை-அக்)",
    "common.rabi": "ரபி (நவ-மார்)",
    "common.zaid": "சாய்ட் (மார்-ஜூன்)",
    "stats.farmers": "பதிவு செய்த விவசாயிகள்",
    "stats.crops": "கண்காணிக்கப்படும் பயிர்கள்",
    "stats.states": "மாநிலங்கள்",
    "stats.schemes": "அரசு திட்டங்கள்",
    "landing.features.heading": "ஒரு விவசாயிக்கு தேவையான அனைத்தும்",
    "landing.features.subheading": "ஒரு தளம், புத்திசாலி விவசாய முடிவுகளுக்கான அனைத்து கருவிகளும்",
    "landing.howItWorks.heading": "இது எப்படி வேலை செய்கிறது",
    "landing.howItWorks.subheading": "சிறந்த விவசாய முடிவுகளுக்கு மூன்று எளிய படிகள்",
    "landing.howItWorks.step1.title": "உங்கள் பண்ணை விவரங்களை உள்ளிடுங்கள்",
    "landing.howItWorks.step1.desc": "உங்கள் மண் வகை, இருப்பிடம் மற்றும் நீர் கிடைக்கும் தன்மை.",
    "landing.howItWorks.step2.title": "புத்திசாலி பரிந்துரைகளைப் பெறுங்கள்",
    "landing.howItWorks.step2.desc": "எங்கள் அமைப்பு வழங்கல்-தேவை தரவை பகுப்பாய்வு செய்கிறது.",
    "landing.howItWorks.step3.title": "சிறப்பாக வளர்த்து சம்பாதியுங்கள்",
    "landing.howItWorks.step3.desc": "ஆலோசனையைப் பின்பற்றுங்கள், விலைகளைக் கண்காணியுங்கள்.",
    "landing.cta.heading": "இன்றே புத்திசாலி பயிர் முடிவுகளை எடுக்கத் தொடங்குங்கள்",
    "landing.cta.desc": "CropGuide India பயன்படுத்தும் லட்சக்கணக்கான இந்திய விவசாயிகளுடன் இணையுங்கள்.",
    "advisor.farmDetails": "பண்ணை விவரங்கள்",
    "advisor.farmDetailsDesc": "கீழே உங்கள் பண்ணை தகவலை உள்ளிடவும்",
    "advisor.soilPh": "pH வரம்பு",
    "advisor.characteristics": "பண்புகள்",
    "advisor.commonRegions": "பொதுவான பகுதிகள்",
    "advisor.noResults": "பயிர்கள் இல்லை",
    "advisor.noResultsDesc": "தேர்ந்தெடுக்கப்பட்ட கலவைக்கு பொருத்தமான பயிர்கள் இல்லை.",
    "advisor.emptyTitle": "உங்கள் பண்ணை விவரங்களைத் தேர்ந்தெடுக்கவும்",
    "advisor.emptyDesc": "தனிப்பயன் பயிர் பரிந்துரைகளைப் பெற படிவத்தை நிரப்பவும்.",
    "advisor.waterLow": "மழை நீர் / நீர்ப்பாசனம் இல்லை",
    "advisor.waterMedium": "பருவகால நீர்ப்பாசனம்",
    "advisor.waterHigh": "ஆண்டு முழுவதும் நீர்ப்பாசனம்",
    "advisor.moreDetails": "மேலும் விவரங்கள்",
    "advisor.showLess": "குறைவாகக் காட்டு",
    "advisor.temp": "வெப்பநிலை",
    "market.rising": "விலைகள் உயர்கின்றன",
    "market.stable": "விலைகள் நிலையானவை",
    "market.falling": "விலைகள் குறைகின்றன",
    "market.chartTitle": "விலை ஒப்பீடு: தற்போதைய vs MSP",
    "market.chartDesc": "தற்போதைய சந்தை விலையின் அடிப்படையில் முதன்மை பயிர்கள்",
    "market.allPrices": "அனைத்து பயிர் விலைகள்",
    "schemes.helpTitle": "விண்ணப்பிக்க உதவி வேண்டுமா?",
    "schemes.helpDesc": "கிசான் அழைப்பு மையத்தை அழைக்கவும் {phone} (கட்டணமில்லை). 22 மொழிகளில் கிடைக்கும்.",
    "footer.quickLinks": "விரைவு இணைப்புகள்",
    "footer.contact": "தொடர்பு",
  },
  te: {
    "nav.home": "హోమ్",
    "nav.advisor": "పంట సలహాదారు",
    "nav.market": "మార్కెట్ ధరలు",
    "nav.schemes": "ప్రభుత్వ పథకాలు",
    "nav.language": "భాష",
    "hero.title": "తెలివిగా సాగు, మెరుగైన ఆదాయం",
    "hero.subtitle": "మీ నేల, ప్రాంతీయ డిమాండ్ మరియు మార్కెట్ పరిస్థితుల ఆధారంగా సరైన పంటలను ఎంచుకోవడంలో సహాయపడే ప్రభుత్వ ధృవీకరించబడిన పంట సలహా.",
    "hero.cta": "పంట సిఫార్సులు పొందండి",
    "hero.certified": "ప్రభుత్వ ధృవీకరించబడిన వేదిక",
    "features.soil.title": "నేల విశ్లేషణ",
    "features.soil.desc": "మీ నేల రకం ఆధారంగా పంట సిఫార్సులు పొందండి.",
    "features.demand.title": "సరఫరా-డిమాండ్ సమతుల్యత",
    "features.demand.desc": "ఇతరులు ఏమి పండిస్తున్నారో తెలుసుకోండి.",
    "features.price.title": "మార్కెట్ ధరలు",
    "features.price.desc": "నిజ-సమయ పంట ధరలు మరియు ధోరణులను ట్రాక్ చేయండి.",
    "features.weather.title": "వాతావరణ సలహా",
    "features.weather.desc": "స్థానిక వాతావరణ సూచనలు పొందండి.",
    "features.scheme.title": "ప్రభుత్వ పథకాలు",
    "features.scheme.desc": "అన్ని ప్రభుత్వ సబ్సిడీలు ఒకే చోట.",
    "features.water.title": "నీటి నిర్వహణ",
    "features.water.desc": "పంట అవసరాల ఆధారంగా నీటిపారుదలను ఆప్టిమైజ్ చేయండి.",
    "advisor.title": "పంట సలహాదారు",
    "advisor.subtitle": "వ్యక్తిగత పంట సిఫార్సుల కోసం వివరాలు నమోదు చేయండి",
    "advisor.soil": "నేల రకం",
    "advisor.state": "రాష్ట్రం",
    "advisor.water": "నీటి లభ్యత",
    "advisor.submit": "సిఫార్సులు పొందండి",
    "advisor.results": "సిఫార్సు చేయబడిన పంటలు",
    "advisor.profitability": "లాభదాయకత స్కోర్",
    "advisor.demand": "డిమాండ్",
    "advisor.supply": "సరఫరా స్థితి",
    "advisor.recommendation": "సిఫార్సు",
    "advisor.waterReq": "నీటి అవసరం",
    "advisor.growingPeriod": "పెరుగుదల కాలం",
    "advisor.days": "రోజులు",
    "advisor.season": "సీజన్",
    "advisor.tips": "చిట్కాలు",
    "advisor.selectSoil": "నేల రకాన్ని ఎంచుకోండి",
    "advisor.selectState": "రాష్ట్రాన్ని ఎంచుకోండి",
    "advisor.selectWater": "నీటి లభ్యతను ఎంచుకోండి",
    "market.title": "మార్కెట్ ధరలు",
    "market.subtitle": "ప్రస్తుత పంట ధరలను ట్రాక్ చేయండి",
    "market.msp": "MSP",
    "market.current": "ప్రస్తుత ధర",
    "market.trend": "ధోరణి",
    "market.perQuintal": "క్వింటాల్‌కు",
    "schemes.title": "ప్రభుత్వ పథకాలు",
    "schemes.subtitle": "వ్యవసాయ మద్దతు పథకాలను కనుగొనండి",
    "schemes.eligibility": "అర్హత",
    "schemes.benefit": "ప్రయోజనం",
    "schemes.apply": "మరింత తెలుసుకోండి",
    "schemes.all": "అన్నీ",
    "schemes.subsidy": "సబ్సిడీ",
    "schemes.insurance": "బీమా",
    "schemes.credit": "రుణం",
    "schemes.infrastructure": "మౌలిక సదుపాయాలు",
    "schemes.training": "శిక్షణ",
    "footer.tagline": "స్మార్ట్ పంట సలహాతో భారత రైతులను సాధికారత",
    "footer.rights": "అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి. భారత ప్రభుత్వ చొరవ.",
    "common.low": "తక్కువ",
    "common.medium": "మధ్యస్థం",
    "common.high": "ఎక్కువ",
    "common.veryHigh": "చాలా ఎక్కువ",
    "common.shortage": "కొరత",
    "common.balanced": "సమతుల్యం",
    "common.surplus": "మిగులు",
    "common.safe": "సిఫార్సు",
    "common.caution": "పర్యవేక్షణ",
    "common.warning": "నివారించండి",
    "common.kharif": "ఖరీఫ్ (జూలై-అక్టో)",
    "common.rabi": "రబీ (నవం-మార్చి)",
    "common.zaid": "జాయద్ (మార్చి-జూన్)",
    "stats.farmers": "నమోదైన రైతులు",
    "stats.crops": "ట్రాక్ చేయబడిన పంటలు",
    "stats.states": "రాష్ట్రాలు",
    "stats.schemes": "ప్రభుత్వ పథకాలు",
    "landing.features.heading": "రైతుకు అవసరమైన ప్రతిదీ",
    "landing.features.subheading": "ఒక వేదిక, తెలివైన వ్యవసాయ నిర్ణయాలకు అన్ని సాధనాలు",
    "landing.howItWorks.heading": "ఇది ఎలా పని చేస్తుంది",
    "landing.howItWorks.subheading": "మెరుగైన వ్యవసాయ నిర్ణయాలకు మూడు సులభ దశలు",
    "landing.howItWorks.step1.title": "మీ పొలం వివరాలను నమోదు చేయండి",
    "landing.howItWorks.step1.desc": "మీ నేల రకం, ప్రదేశం మరియు నీటి లభ్యత చెప్పండి.",
    "landing.howItWorks.step2.title": "తెలివైన సిఫార్సులు పొందండి",
    "landing.howItWorks.step2.desc": "మా వ్యవస్థ సరఫరా-డిమాండ్ డేటాను విశ్లేషిస్తుంది.",
    "landing.howItWorks.step3.title": "బాగా పండించండి మరియు సంపాదించండి",
    "landing.howItWorks.step3.desc": "సలహాను అనుసరించండి, ధరలను ట్రాక్ చేయండి.",
    "landing.cta.heading": "ఈ రోజే తెలివైన పంట నిర్ణయాలు తీసుకోవడం ప్రారంభించండి",
    "landing.cta.desc": "CropGuide India ఉపయోగిస్తున్న లక్షలాది భారత రైతులతో చేరండి.",
    "advisor.farmDetails": "పొలం వివరాలు",
    "advisor.farmDetailsDesc": "క్రింద మీ పొలం సమాచారం నమోదు చేయండి",
    "advisor.soilPh": "pH పరిధి",
    "advisor.characteristics": "లక్షణాలు",
    "advisor.commonRegions": "సాధారణ ప్రాంతాలు",
    "advisor.noResults": "పంటలు కనుగొనబడలేదు",
    "advisor.noResultsDesc": "ఎంపిక చేసిన కలయికకు తగిన పంటలు కనుగొనబడలేదు.",
    "advisor.emptyTitle": "మీ పొలం వివరాలను ఎంచుకోండి",
    "advisor.emptyDesc": "వ్యక్తిగత పంట సిఫార్సులు పొందడానికి ఫారమ్ నింపండి.",
    "advisor.waterLow": "వర్షాధారం / నీటిపారుదల లేదు",
    "advisor.waterMedium": "కాలానుగుణ నీటిపారుదల",
    "advisor.waterHigh": "ఏడాది పొడవునా నీటిపారుదల",
    "advisor.moreDetails": "మరిన్ని వివరాలు",
    "advisor.showLess": "తక్కువ చూపించు",
    "advisor.temp": "ఉష్ణోగ్రత",
    "market.rising": "ధరలు పెరుగుతున్నాయి",
    "market.stable": "ధరలు స్థిరంగా ఉన్నాయి",
    "market.falling": "ధరలు తగ్గుతున్నాయి",
    "market.chartTitle": "ధర పోలిక: ప్రస్తుతం vs MSP",
    "market.chartDesc": "ప్రస్తుత మార్కెట్ ధర ప్రకారం ముఖ్య పంటలు",
    "market.allPrices": "అన్ని పంట ధరలు",
    "schemes.helpTitle": "దరఖాస్తు చేయడంలో సహాయం కావాలా?",
    "schemes.helpDesc": "కిసాన్ కాల్ సెంటర్‌కు కాల్ చేయండి {phone} (టోల్-ఫ్రీ). 22 భాషల్లో అందుబాటులో.",
    "footer.quickLinks": "శీఘ్ర లింకులు",
    "footer.contact": "సంప్రదించండి",
  },
  mr: {
    "nav.home": "मुख्यपृष्ठ",
    "nav.advisor": "पीक सल्लागार",
    "nav.market": "बाजारभाव",
    "nav.schemes": "सरकारी योजना",
    "nav.language": "भाषा",
    "hero.title": "स्मार्ट शेती, चांगली कमाई",
    "hero.subtitle": "तुमच्या मातीच्या प्रकारावर, प्रादेशिक मागणीवर आणि बाजार परिस्थितीवर आधारित योग्य पिके निवडण्यासाठी सरकार प्रमाणित पीक सल्ला.",
    "hero.cta": "पीक शिफारशी मिळवा",
    "hero.certified": "सरकार प्रमाणित व्यासपीठ",
    "features.soil.title": "माती विश्लेषण",
    "features.soil.desc": "तुमच्या मातीच्या प्रकारावर आधारित पीक शिफारशी मिळवा.",
    "features.demand.title": "पुरवठा-मागणी संतुलन",
    "features.demand.desc": "इतर शेतकरी काय पिकवतात ते जाणून घ्या.",
    "features.price.title": "बाजारभाव",
    "features.price.desc": "रिअल-टाइम पीक भाव आणि ट्रेंड ट्रॅक करा.",
    "features.weather.title": "हवामान सल्ला",
    "features.weather.desc": "स्थानिक हवामान अंदाज मिळवा.",
    "features.scheme.title": "सरकारी योजना",
    "features.scheme.desc": "सर्व सरकारी अनुदाने एकाच ठिकाणी.",
    "features.water.title": "पाणी व्यवस्थापन",
    "features.water.desc": "पिकांच्या गरजेनुसार सिंचन अनुकूल करा.",
    "advisor.title": "पीक सल्लागार",
    "advisor.subtitle": "वैयक्तिक पीक शिफारशींसाठी तपशील भरा",
    "advisor.soil": "मातीचा प्रकार",
    "advisor.state": "राज्य",
    "advisor.water": "पाणी उपलब्धता",
    "advisor.submit": "शिफारशी मिळवा",
    "advisor.results": "शिफारस केलेली पिके",
    "advisor.profitability": "नफा गुणांक",
    "advisor.demand": "मागणी",
    "advisor.supply": "पुरवठा स्थिती",
    "advisor.recommendation": "शिफारस",
    "advisor.waterReq": "पाणी आवश्यकता",
    "advisor.growingPeriod": "वाढीचा कालावधी",
    "advisor.days": "दिवस",
    "advisor.season": "हंगाम",
    "advisor.tips": "टिप्स",
    "advisor.selectSoil": "मातीचा प्रकार निवडा",
    "advisor.selectState": "राज्य निवडा",
    "advisor.selectWater": "पाणी उपलब्धता निवडा",
    "market.title": "बाजारभाव",
    "market.subtitle": "सध्याचे पीक भाव ट्रॅक करा",
    "market.msp": "MSP",
    "market.current": "सध्याचा भाव",
    "market.trend": "ट्रेंड",
    "market.perQuintal": "प्रति क्विंटल",
    "schemes.title": "सरकारी योजना",
    "schemes.subtitle": "कृषी सहाय्य योजना शोधा",
    "schemes.eligibility": "पात्रता",
    "schemes.benefit": "लाभ",
    "schemes.apply": "अधिक जाणून घ्या",
    "schemes.all": "सर्व",
    "schemes.subsidy": "अनुदान",
    "schemes.insurance": "विमा",
    "schemes.credit": "कर्ज",
    "schemes.infrastructure": "पायाभूत सुविधा",
    "schemes.training": "प्रशिक्षण",
    "footer.tagline": "स्मार्ट पीक सल्ल्याने भारतीय शेतकऱ्यांना सक्षम करणे",
    "footer.rights": "सर्व हक्क राखीव. भारत सरकारचा उपक्रम.",
    "common.low": "कमी",
    "common.medium": "मध्यम",
    "common.high": "जास्त",
    "common.veryHigh": "खूप जास्त",
    "common.shortage": "तुटवडा",
    "common.balanced": "संतुलित",
    "common.surplus": "अधिशेष",
    "common.safe": "शिफारस",
    "common.caution": "निरीक्षण",
    "common.warning": "टाळा",
    "common.kharif": "खरीप (जुलै-ऑक्टो)",
    "common.rabi": "रब्बी (नोव्हें-मार्च)",
    "common.zaid": "उन्हाळी (मार्च-जून)",
    "stats.farmers": "नोंदणीकृत शेतकरी",
    "stats.crops": "ट्रॅक केलेली पिके",
    "stats.states": "राज्ये",
    "stats.schemes": "सरकारी योजना",
    "landing.features.heading": "शेतकऱ्याला लागणारे सर्व काही",
    "landing.features.subheading": "एक व्यासपीठ, स्मार्ट शेती निर्णयांसाठी सर्व साधने",
    "landing.howItWorks.heading": "हे कसे काम करते",
    "landing.howItWorks.subheading": "चांगल्या शेती निर्णयांसाठी तीन सोप्या पायऱ्या",
    "landing.howItWorks.step1.title": "तुमच्या शेताचा तपशील द्या",
    "landing.howItWorks.step1.desc": "तुमच्या मातीचा प्रकार, ठिकाण आणि पाणी उपलब्धता सांगा.",
    "landing.howItWorks.step2.title": "स्मार्ट शिफारशी मिळवा",
    "landing.howItWorks.step2.desc": "आमची प्रणाली पुरवठा-मागणी डेटाचे विश्लेषण करते.",
    "landing.howItWorks.step3.title": "चांगले पिकवा आणि कमवा",
    "landing.howItWorks.step3.desc": "सल्ल्याचे पालन करा, भाव ट्रॅक करा आणि सरकारी योजना वापरा.",
    "landing.cta.heading": "आजच स्मार्ट पीक निर्णय घ्या",
    "landing.cta.desc": "CropGuide India वापरणाऱ्या लाखो भारतीय शेतकऱ्यांसोबत सामील व्हा.",
    "advisor.farmDetails": "शेताचा तपशील",
    "advisor.farmDetailsDesc": "खाली तुमच्या शेताची माहिती भरा",
    "advisor.soilPh": "pH श्रेणी",
    "advisor.characteristics": "वैशिष्ट्ये",
    "advisor.commonRegions": "सामान्य प्रदेश",
    "advisor.noResults": "पिके आढळली नाहीत",
    "advisor.noResultsDesc": "निवडलेल्या संयोजनासाठी योग्य पिके आढळली नाहीत.",
    "advisor.emptyTitle": "तुमच्या शेताचा तपशील निवडा",
    "advisor.emptyDesc": "वैयक्तिक पीक शिफारशींसाठी फॉर्म भरा.",
    "advisor.waterLow": "पावसावर अवलंबून / सिंचन नाही",
    "advisor.waterMedium": "हंगामी सिंचन",
    "advisor.waterHigh": "वर्षभर सिंचन",
    "advisor.moreDetails": "अधिक तपशील",
    "advisor.showLess": "कमी दाखवा",
    "advisor.temp": "तापमान",
    "market.rising": "भाव वाढत आहेत",
    "market.stable": "भाव स्थिर आहेत",
    "market.falling": "भाव घसरत आहेत",
    "market.chartTitle": "भाव तुलना: सध्याचा बनाम MSP",
    "market.chartDesc": "सध्याच्या बाजारभावानुसार प्रमुख पिके",
    "market.allPrices": "सर्व पिकांचे भाव",
    "schemes.helpTitle": "अर्ज करण्यासाठी मदत हवी?",
    "schemes.helpDesc": "किसान कॉल सेंटरवर कॉल करा {phone} (टोल-फ्री). 22 भाषांमध्ये उपलब्ध.",
    "footer.quickLinks": "जलद दुवे",
    "footer.contact": "संपर्क",
  },
  bn: {
    "nav.home": "হোম",
    "nav.advisor": "ফসল উপদেষ্টা",
    "nav.market": "বাজার দর",
    "nav.schemes": "সরকারি প্রকল্প",
    "nav.language": "ভাষা",
    "hero.title": "বুদ্ধিমান চাষ, ভালো আয়",
    "hero.subtitle": "আপনার মাটি, আঞ্চলিক চাহিদা এবং বাজার পরিস্থিতির উপর ভিত্তি করে সঠিক ফসল বেছে নিতে সাহায্যকারী সরকার প্রত্যয়িত ফসল পরামর্শ.",
    "hero.cta": "ফসল সুপারিশ পান",
    "hero.certified": "সরকার প্রত্���য়িত মঞ্চ",
    "features.soil.title": "মাটি বিশ্লেষণ",
    "features.soil.desc": "আপনার মাটির ধরনের উপর ভিত্তি করে ফসল সুপারিশ পান.",
    "features.demand.title": "যোগান-চাহিদা ভারসাম্য",
    "features.demand.desc": "অন্যরা কী চাষ করছে জানুন.",
    "features.price.title": "বাজার দর",
    "features.price.desc": "রিয়েল-টাইম ফসলের দর এবং প্রবণতা ট্র্যাক করুন.",
    "features.weather.title": "আবহাওয়া পরামর্শ",
    "features.weather.desc": "স্থানীয় আবহাওয়ার পূর্বাভাস পান.",
    "features.scheme.title": "সরকারি প্রকল্প",
    "features.scheme.desc": "সব সরকারি ভর্তুকি একই জায়গায়.",
    "features.water.title": "জল ব্যবস্থাপনা",
    "features.water.desc": "ফসলের চাহিদার উপর ভিত্তি করে সেচ অপ্টিমাইজ করুন.",
    "advisor.title": "ফসল উপদেষ্টা",
    "advisor.subtitle": "ব্যক্তিগত ফসল সুপারিশের জন্য বিবরণ লিখুন",
    "advisor.soil": "মাটির ধরন",
    "advisor.state": "রাজ্য",
    "advisor.water": "জলের প্রাপ্যতা",
    "advisor.submit": "সুপারিশ পান",
    "advisor.results": "সুপারিশকৃত ফসল",
    "advisor.profitability": "লাভজনকতা স্কোর",
    "advisor.demand": "চাহিদা",
    "advisor.supply": "যোগান অবস্থা",
    "advisor.recommendation": "সুপারিশ",
    "advisor.waterReq": "জলের প্রয়োজন",
    "advisor.growingPeriod": "বৃদ্ধির সময়কাল",
    "advisor.days": "দিন",
    "advisor.season": "মৌসুম",
    "advisor.tips": "পরামর্শ",
    "advisor.selectSoil": "মাটির ধরন নির্বাচন করুন",
    "advisor.selectState": "রাজ্য নির্বাচন করুন",
    "advisor.selectWater": "জলের প্রাপ্যতা নির্বাচন করুন",
    "market.title": "বাজার দর",
    "market.subtitle": "বর্তমান ফসলের দর ট্র্যাক করুন",
    "market.msp": "MSP",
    "market.current": "বর্তমান দর",
    "market.trend": "প্রবণতা",
    "market.perQuintal": "প্রতি কুইন্টাল",
    "schemes.title": "সরকারি প্রকল্প",
    "schemes.subtitle": "কৃষি সহায়তা প্রকল্প খুঁজুন",
    "schemes.eligibility": "যোগ্যতা",
    "schemes.benefit": "সুবিধা",
    "schemes.apply": "আরও জানুন",
    "schemes.all": "সব",
    "schemes.subsidy": "ভর্তুকি",
    "schemes.insurance": "বীমা",
    "schemes.credit": "ঋণ",
    "schemes.infrastructure": "অবকাঠামো",
    "schemes.training": "প্রশিক্ষণ",
    "footer.tagline": "স্মার্ট ফসল পরামর্শ দিয়ে ভারতীয় কৃষকদের ক্ষমতায়ন",
    "footer.rights": "সর্বস্বত্ব সংরক্ষিত। ভারত সরকারের উদ্যোগ.",
    "common.low": "কম",
    "common.medium": "মাঝারি",
    "common.high": "বেশি",
    "common.veryHigh": "অনেক বেশি",
    "common.shortage": "ঘাটতি",
    "common.balanced": "সুষম",
    "common.surplus": "উদ্বৃত্ত",
    "common.safe": "সুপারিশকৃত",
    "common.caution": "পর্যবেক্ষণ",
    "common.warning": "এড়িয়ে চলুন",
    "common.kharif": "খারিফ (জুলাই-অক্টো)",
    "common.rabi": "রবি (নভে-মার্চ)",
    "common.zaid": "জায়েদ (মার্চ-জুন)",
    "stats.farmers": "নিবন্ধিত কৃষক",
    "stats.crops": "ট্র্যাক করা ফসল",
    "stats.states": "রাজ্য",
    "stats.schemes": "সরকারি প্রকল্প",
    "landing.features.heading": "একজন কৃষকের যা প্রয়োজন সবকিছু",
    "landing.features.subheading": "একটি প্ল্যাটফর্ম, স্মার্ট কৃষি সিদ্ধান্তের জন্য সব সরঞ্জাম",
    "landing.howItWorks.heading": "এটি কীভাবে কাজ করে",
    "landing.howItWorks.subheading": "ভালো চাষের সিদ্ধান্তের জন্য তিনটি সহজ ধাপ",
    "landing.howItWorks.step1.title": "আপনার খামারের বিবরণ দিন",
    "landing.howItWorks.step1.desc": "আপনার মাটির ধরন, অবস্থান এবং জলের প্রাপ্যতা জানান.",
    "landing.howItWorks.step2.title": "স্মার্ট সুপারিশ পান",
    "landing.howItWorks.step2.desc": "আমাদের সিস্টেম যোগান-চাহিদা ডেটা বিশ্লেষণ করে.",
    "landing.howItWorks.step3.title": "ভালো ফলান এবং উপার্জন করুন",
    "landing.howItWorks.step3.desc": "পরামর্শ অনুসরণ করুন, দর ট্র্যাক করুন এবং সরকারি প্রকল্প ব্যবহার করুন.",
    "landing.cta.heading": "আজই স্মার্ট ফসলের সিদ্ধান্ত নিন",
    "landing.cta.desc": "CropGuide India ব্যবহারকারী লক্ষ লক্ষ ভারতীয় কৃষকদের সাথে যোগ দিন.",
    "advisor.farmDetails": "খামারের বিবরণ",
    "advisor.farmDetailsDesc": "নীচে আপনার খামারের তথ্য লিখুন",
    "advisor.soilPh": "pH পরিসীমা",
    "advisor.characteristics": "বৈশিষ্ট্য",
    "advisor.commonRegions": "সাধারণ অঞ্চল",
    "advisor.noResults": "ফসল পাওয়া যায়নি",
    "advisor.noResultsDesc": "নির্বাচিত সংমিশ্রণের জন্য কোনো উপযুক্ত ফসল পাওয়া যায়নি.",
    "advisor.emptyTitle": "আপনার খামারের বিবরণ নির্বাচন করুন",
    "advisor.emptyDesc": "ব্যক্তিগত ফসল সুপারিশ পেতে ফর্ম পূরণ করুন.",
    "advisor.waterLow": "বৃষ্টি নির্ভর / সেচ নেই",
    "advisor.waterMedium": "মৌসুমী সেচ",
    "advisor.waterHigh": "সারা বছর সেচ",
    "advisor.moreDetails": "আরও বিবরণ",
    "advisor.showLess": "কম দেখান",
    "advisor.temp": "তাপমাত্রা",
    "market.rising": "দর বাড়ছে",
    "market.stable": "দর স্থিতিশীল",
    "market.falling": "দর কমছে",
    "market.chartTitle": "দর তুলনা: বর্তমান vs MSP",
    "market.chartDesc": "বর্তমান বাজার দর অনুযায়ী প্রধান ফসল",
    "market.allPrices": "সব ফসলের দর",
    "schemes.helpTitle": "আবেদনে সাহায্য চাই?",
    "schemes.helpDesc": "কিসান কল সেন্টারে কল করুন {phone} (টোল-ফ্রি). ২২ ভাষায় পাওয়া যায়.",
    "footer.quickLinks": "দ্রুত লিংক",
    "footer.contact": "যোগাযোগ",
  },
  }

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: TranslationKey) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = useCallback(
    (key: TranslationKey): string => {
      return translations[language]?.[key] || translations.en[key] || key
    },
    [language],
  )

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
