// TypeScript interfaces for AI advisory data

/** Categories of farming advice generated by the AI */
export type AdvisoryCategory =
  | "planting"
  | "irrigation"
  | "fertilizer"
  | "market"
  | "pest"

/** A single piece of AI-generated farming advice */
export interface AdvisoryItem {
  /** Which farming category this advice belongs to */
  category: AdvisoryCategory
  /** Short title summarizing the advice */
  title: string
  /** Full advice text in farmer-friendly language */
  advice: string
  /** Optional urgency level: high (act now), medium (soon), low (informational) */
  urgency?: "high" | "medium" | "low"
}

/** Context fed into the AI to generate relevant advice */
export interface AdvisoryContext {
  /** Farmer's primary crop (e.g. "wheat", "rice") */
  cropType?: string
  /** Current temperature in °C */
  temperature?: number
  /** Relative humidity percentage */
  humidity?: number
  /** Precipitation / rain chance percentage */
  rainfall?: number
  /** Current crop market price in INR per quintal */
  marketPrice?: number
  /** Percentage price change vs previous day */
  priceChange?: number
  /** Current calendar season */
  season?: "summer" | "monsoon" | "winter" | "spring"
  /** Indian state / region name */
  location?: string
}

/** Full response from the AI advisory service */
export interface AdvisoryData {
  items: AdvisoryItem[]
  /** Unix timestamp (ms) of when the advice was generated */
  generatedAt: number
  /** Context that was used to generate this advice */
  context: AdvisoryContext
}
